ExtNetNoIframeDemo/Controllers/Controller1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ext.Net.MVC;

namespace ExtNetNoIframeDemo.Controllers
{
    public class Controller1Controller : Controller
    {
        // GET: Controller1/PartialView1
        public Ext.Net.MVC.PartialViewResult PartialView1(string containerId)
        {
            return new Ext.Net.MVC.PartialViewResult(containerId)
            {
                ClearContainer = true,
                WrapByScriptTag = false
            };
        }

        // GET: Controller1/SimulateAjax
        public ActionResult SimulateAjax()
        {
            return Json(null, JsonRequestBehavior.AllowGet);
        }
    }
}

ExtNetNoIframeDemo/Controllers/Controller2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ext.Net.MVC;

namespace ExtNetNoIframeDemo.Controllers
{
    public class Controller2Controller : Controller
    {
        // GET: Controller2/PartialView2
        public Ext.Net.MVC.PartialViewResult PartialView2(string containerId)
        {
            return new Ext.Net.MVC.PartialViewResult(containerId)
            {
                ClearContainer = true,
                WrapByScriptTag = false
            };
        }
    }
}

ExtNetNoIframeDemo/Controllers/Controller3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ext.Net.MVC;

namespace ExtNetNoIframeDemo.Controllers
{
    public class Controller3Controller : Controller
    {
        // GET: Controller3/PartialView3
        public Ext.Net.MVC.PartialViewResult PartialView3(string containerId)
        {
            return new Ext.Net.MVC.PartialViewResult(containerId)
            {
                ClearContainer = true,
                WrapByScriptTag = false
            };
        }

    }
}

ExtNetNoIframeDemo/Controllers/Controller4Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ext.Net.MVC;

namespace ExtNetNoIframeDemo.Controllers
{
    public class Controller4Controller : Controller
    {
        // GET: Controller4/PartialView4
        public Ext.Net.MVC.PartialViewResult PartialView4(string containerId)
        {
            return new Ext.Net.MVC.PartialViewResult(containerId)
            {
                ClearContainer = true,
                WrapByScriptTag = false
            };
        }
    }
}

ExtNetNoIframeDemo/Controllers/DialogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ExtNetNoIframeDemo.Controllers
{
    public class DialogController : Controller
    {
        // GET: Dialog/Index
        public Ext.Net.MVC.PartialViewResult Index(string containerId)
        {
            return new Ext.Net.MVC.PartialViewResult(containerId)
            {
                ClearContainer = true,
                WrapByScriptTag = false,
                ViewName = "_Dialog"
            };
        }
    }
}

ExtNetNoIframeDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExtNetNoIframeDemo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public Ext.Net.MVC.PartialViewResult MainMenu1(string containerId)
        {
            return new Ext.Net.MVC.PartialViewResult(containerId)
            {
                ClearContainer = true,
                WrapByScriptTag = false
            };
        }

        public Ext.Net.MVC.PartialViewResult MainMenu2(string containerId)
        {
            return new Ext.Net.MVC.PartialViewResult(containerId)
            {
                ClearContainer = true,
                WrapByScriptTag = false
            };
        }
    }
}

ExtNetNoIframeDemo/Views/Controller1/PartialView1.cshtml
@Html.Partial("_SubMenu")


@(Html.X().Panel()
    .Title("PartialView1 redered as partial view")
    .BodyPadding(5)
    .Frame(true)
    .Items(
        Html.X().Button().Text("Simulate ajax").Icon(Icon.Disk)
        .Listeners(ls =>
        {
            ls.Click.Fn = "simulateAjax";
        })
    )
    
)

<script type="text/javascript">

    var simulateAjax = function () {
        Ext.Ajax.request({
            method: "GET",
            url: '@Url.Action("SimulateAjax", "Controller1")',
            cleanRequest: true,
            success: function () { console.log('simulate ajax success') },
            failure: function () { console.log('simulate ajax fail!') },
        });
    }

</script>

ExtNetNoIframeDemo/Views/Controller2/PartialView2.cshtml
@{
    var X = Html.X();
}

@Html.Partial("_SubMenu")

@(Html.X().Panel()
    .ID("mainContainer2")
    .Title("PartialView2 redered as partial view")
    .Layout(LayoutType.HBox)
    .Frame(true)
    .BodyPadding(5)
    .MarginSpec("0 0 5 0")
)

ExtNetNoIframeDemo/Views/Controller3/PartialView3.cshtml
@Html.Partial("_SubMenu2")

@(Html.X().Panel()
    .Title("PartialView3 redered as partial view")
    .BodyPadding(5)
    .Frame(true)
    .Items(
       Html.X().Button()
            .Text("Show Window (Client Event)")
            .Icon(Icon.Application)
            .Handler("App.Window1.show();")
    )
)
@(Html.X().Window()
    .Hidden(true)
    .ID("Window1")
    .Title("Dialog demo")
    .Icon(Icon.Application)
    .Height(185)
    .Width(350)
    .BodyPadding(5)
    .Modal(true)
    .Items(
        Html.X().Container()
            .ID("popupContainer")
            .Layout(LayoutType.Border)
            .Padding(5)
            .Height(450)
            .Loader(Html.X().ComponentLoader()
                .Url(Url.Action("Index", "Dialog"))
                .Mode(LoadMode.Script)
                .Params(new { containerId = "popupContainer" })
                .LoadMask(lm => lm.ShowMask = true)
            )
        ) // /Items
)

ExtNetNoIframeDemo/Views/Controller4/PartialView4.cshtml
@Html.Partial("_SubMenu2")


@(Html.X().Panel()
    .Title("PartialView4 redered as partial view")
    .BodyPadding(5)
    .Frame(true)
    
)

ExtNetNoIframeDemo/Views/Home/Index.cshtml
@using Ext.Net
@using Ext.Net.MVC

@{
    ViewBag.Title = "Home";
}

@(Html.X().Container()
    .ID("subMenuContainer")
    .Layout(LayoutType.Border)
    .Padding(5)
    .Height(450)
    .Loader(Html.X().ComponentLoader()
        .Url(Url.Action("MainMenu1", "Home"))
        .Mode(LoadMode.Script)
        .Params(new { containerId = "subMenuContainer" })
        .LoadMask(lm => lm.ShowMask = true)
    )
)

ExtNetNoIframeDemo/Views/Home/MainMenu1.cshtml
@{
    var X = Html.X();
}

@(X.Panel()
    .Region(Region.North)
    .Layout(LayoutType.HBox)
    .Frame(true)
    .BodyPadding(5)
    .MarginSpec("0 0 5 0")
    .Defaults(X.Parameter().Name("margin").Value("0 5 0 0").Mode(ParameterMode.Value))
    .LayoutConfig(new HBoxLayoutConfig { Align = HBoxAlign.Middle, Pack = BoxPack.Start })
    .Items(
        X.Label().Text("PartialView MainMenu1"),
        X.Button().Text("SubMenu1").Flat(true).DirectEvents(e1 =>
        {
            e1.Click.Url = Url.Action("PartialView1", "Controller1");
            e1.Click.ExtraParams.Add(new { containerId = "mainContainer" });
        }),
        X.Button().Text("SubMenu2").Flat(true).DirectEvents(e2 =>
        {
            e2.Click.Url = Url.Action("PartialView3", "Controller3");
            e2.Click.ExtraParams.Add(new { containerId = "mainContainer" });
        })
))

@(Html.X().Container()
    .ID("mainContainer")
    .Layout(LayoutType.Border)
    //.Padding(5)
    .Height(400)
        .Loader(Html.X().ComponentLoader()
            .Url(Url.Action("PartialView1", "Controller1"))
            .Mode(LoadMode.Script)
            .Params(new { containerId = "mainContainer" })
            .LoadMask(lm => lm.ShowMask = true)
        )
)

ExtNetNoIframeDemo/Views/Home/MainMenu2.cshtml
@{
    var X = Html.X();
}

@(X.Panel()
    .Layout(LayoutType.HBox)
    .Frame(true)
    .BodyPadding(5)
    .MarginSpec("0 0 5 0")
    .Defaults(X.Parameter().Name("margin").Value("0 5 0 0").Mode(ParameterMode.Value))
    .LayoutConfig(new HBoxLayoutConfig { Align = HBoxAlign.Middle, Pack = BoxPack.Start })
    .Items(
        X.Label().Text("PartialView MainMenu2"),
        X.Button().Text("SubMenu3").Flat(true).DirectEvents(e1 =>
        {
            e1.Click.Url = Url.Action("PartialView3", "Controller3");
            e1.Click.ExtraParams.Add(new { containerId = "mainContainer" });
        }),
        X.Button().Text("SubMenu4").Flat(true).DirectEvents(e2 =>
        {
            e2.Click.Url = Url.Action("PartialView4", "Controller4");
            e2.Click.ExtraParams.Add(new { containerId = "mainContainer" });
        })
))

@(Html.X().Container()
    .ID("mainContainer")
    .Layout(LayoutType.Border)
    .Padding(5)
    .Height(400)
        .Loader(Html.X().ComponentLoader()
            .Url(Url.Action("PartialView3", "Controller3"))
            .Mode(LoadMode.Script)
            .Params(new { containerId = "mainContainer" })
            .LoadMask(lm => lm.ShowMask = true)
        )
)

ExtNetNoIframeDemo/Views/Shared/_Dialog.cshtml
@{
    Layout = null;
    var X = Html.X();
}

<h1>Simple Ext.NET Window</h1>
<p>Test...</p>

ExtNetNoIframeDemo/Views/Shared/_Layout.cshtml
@using Ext.Net.MVC;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Partials Views demo</title>
    @Styles.Render("~/Content/css")

</head>
<body>
    @{
        var X = Html.X();
    }

    @Html.X().ResourceManager()
    
    <p>This is _Layout</p>

    @Html.Partial("_Menu")
    @RenderBody()

    <footer>
        <p style="padding-left:5px">This is _Layout</p>
    </footer>

    @Scripts.Render("~/bundles/js")
    @RenderSection("scripts", required: false)
</body>
</html>

ExtNetNoIframeDemo/Views/Shared/_Menu.cshtml
@{
    Layout = null;
    var X = Html.X();
}

@(X.Panel()
    .Layout(LayoutType.HBox)
    .Frame(true)
    .BodyPadding(5)
    .MarginSpec("0 0 5 0")
    .Defaults(X.Parameter().Name("margin").Value("0 5 0 0").Mode(ParameterMode.Value))
    .LayoutConfig(new HBoxLayoutConfig { Align = HBoxAlign.Middle, Pack = BoxPack.Start })
    .Items(
        X.Label().Text("_Menu.cshtml (Html.Partial() in _Layout ->"),
        X.Button().Text("MainMenu1").Flat(true).DirectEvents(e1 =>
        {
            e1.Click.Url = Url.Action("MainMenu1", "Home");
            e1.Click.ExtraParams.Add(new { containerId = "subMenuContainer" });
        }),
        X.Button().Text("MainMenu2").Flat(true).DirectEvents(e2 =>
        {
            e2.Click.Url = Url.Action("MainMenu2", "Home");
            e2.Click.ExtraParams.Add(new { containerId = "subMenuContainer" });
        })
))

ExtNetNoIframeDemo/Views/Shared/_SubMenu.cshtml
@{
    Layout = null;
    var X = Html.X();
}

@(X.Panel()
    .Layout(LayoutType.HBox)
    .Frame(true)
    .BodyPadding(5)
    .MarginSpec("0 0 5 0")
    .Defaults(X.Parameter().Name("margin").Value("0 5 0 0").Mode(ParameterMode.Value))
    .LayoutConfig(new HBoxLayoutConfig { Align = HBoxAlign.Middle, Pack = BoxPack.Start })
    .Items(
        X.Label().Text("Rendered by @Html.Partial() ->"),
        X.Button().Text("Show PartialView1").Flat(true).DirectEvents(e1 =>
        {
            e1.Click.Url = Url.Action("PartialView1", "Controller1");
            e1.Click.ExtraParams.Add(new { containerId = "mainContainer" });
        }),
        X.Button().Text("Show PartialView2").Flat(true).DirectEvents(e2 =>
        {
            e2.Click.Url = Url.Action("PartialView2", "Controller2");
            e2.Click.ExtraParams.Add(new { containerId = "mainContainer" });
        })
))

ExtNetNoIframeDemo/Views/Shared/_SubMenu2.cshtml
@{
    Layout = null;
    var X = Html.X();
}

@(X.Panel()
    .Layout(LayoutType.HBox)
    .Frame(true)
    .BodyPadding(5)
    .MarginSpec("0 0 5 0")
    .Defaults(X.Parameter().Name("margin").Value("0 5 0 0").Mode(ParameterMode.Value))
    .LayoutConfig(new HBoxLayoutConfig { Align = HBoxAlign.Middle, Pack = BoxPack.Start })
    .Items(
        X.Label().Text("Rendered by @Html.Partial() ->"),
        X.Button().Text("Show PartialView3").Flat(true).DirectEvents(e1 =>
        {
            e1.Click.Url = Url.Action("PartialView3", "Controller3");
            e1.Click.ExtraParams.Add(new { containerId = "mainContainer" });
        }),
        X.Button().Text("Show PartialView4").Flat(true).DirectEvents(e2 =>
        {
            e2.Click.Url = Url.Action("PartialView4", "Controller4");
            e2.Click.ExtraParams.Add(new { containerId = "mainContainer" });
        })
))